/**
 * models/Transaction.js
 * One document per lifecycle event (one per blockchain transaction).
 */

const mongoose = require("mongoose");

const transactionSchema = new mongoose.Schema(
  {
    // Unique ID generated by the backend (uuid)
    transactionId: { type: String, required: true, unique: true },

    batchId:   { type: String, required: true, uppercase: true, index: true },
    actorId:   { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true },
    actorRole: {
      type: String,
      enum: ["PHARMACY", "DISTRIBUTOR", "MANUFACTURER", "DISPOSAL_AGENT", "REGULATOR"],
      required: true,
    },
    actionType: {
      type: String,
      enum: [
        "RETURNED", "PICKED_UP", "IN_TRANSIT", "RECEIVED",
        "UNDER_INSPECTION", "APPROVED_FOR_DISPOSAL", "DESTROYED",
      ],
      required: true,
    },
    quantity: { type: Number, required: true },
    reason:   { type: String, trim: true },

    location: {
      address: String,
      city:    String,
      state:   String,
      pincode: String,
      gps:     { lat: Number, lng: Number },
    },

    metadata: {
      conditionCode:     { type: String, enum: ["GOOD", "DAMAGED", "TAMPERED", "EXPIRED"] },
      inspectionNotes:   String,
      destructionMethod: { type: String, enum: ["INCINERATION", "LANDFILL", "CHEMICAL", "OTHER"] },
      regulatoryRef:     String,
      temperature:       Number,
      certificateHash:   String,   // IPFS CID of disposal certificate
    },

    // ── Blockchain write result ──────────────────────────────
    txHash:     String,   // Ethereum transaction hash
    blockNumber: Number,  // block number on-chain
    isConfirmed: { type: Boolean, default: false },

    // Server-stamped — client timestamp is NEVER trusted
    serverTimestamp: { type: Date, default: Date.now },
  },
  { timestamps: true }
);

transactionSchema.index({ batchId: 1, serverTimestamp: 1 });
transactionSchema.index({ actorId: 1 });
transactionSchema.index({ txHash: 1 });

module.exports = mongoose.model("Transaction", transactionSchema);
